site_name: COMP423 Course Notes
theme:
  name: material
  
markdown_extensions:
  - pymdownx.highlight  # Enables syntax highlighting for code blocks
  - pymdownx.admonition # Enables admonitions for call-out boxes